asset/config/routes.rb
Rails.application.routes.draw do
  devise_for :logs
  resources :users
  get 'hello/index' => 'hello#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

asset/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

asset/app/models/log.rb
class Log < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

asset/app/models/map.rb
class Map < ApplicationRecord
    geocoded_by :address
    after_validation :geocode
  end

asset/app/models/user.rb
class User < ActiveRecord::Base
    
    mount_uploader :image, ImageUploader

    geocoded_by :address
    after_validation :geocode

    # ...
 # 今日投稿された Post を取得
 scope :created_today, -> { where("created_at >= ?", Time.zone.now.beginning_of_day) }
 # または
 # scope :created_today, -> { where(created_at: Time.zone.now.all_day) }

 # 昨日投稿された Post を取得
 scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }

 # 3日前に投稿された Post を取得
 scope :created_three_days_ago, -> { where(created_at: 3.days.ago.all_day) }

 # 一週間前に投稿された Post を取得
 scope :created_a_week_ago, -> { where(created_at: 1.week.ago.all_day) }

 # 一ヶ月前に投稿された Post を取得
 scope :created_a_month_ago, -> { where(created_at: 1.month.ago.all_day) }

 # ...
end

asset/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

asset/app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end
  end

asset/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_log!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @users = User.all.order("id DESC")
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @map = User.find_by(id: params[:id])
    @latitude = @map.latitude.to_f

    @longitude = @map.longitude.to_f

    @address = @map.address
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:title, :contents, :image, :address, :latitude, :longitude)
    end
end

asset/app/helpers/application_helper.rb
module ApplicationHelper
end

asset/app/helpers/hello_helper.rb
module HelloHelper
end

asset/app/helpers/users_helper.rb
module UsersHelper
end

asset/app/views/hello/index.html.erb
 <div class="container">
    <div class="row">
    
        <div>
            <%= button_to "ログイン", users_path,class: "btn btn-primary", method: :get %>
        </div>

        <div>
            <%= button_to "新規登録", new_log_registration_path,class: "btn btn-primary", method: :get %>
        </div>
    
    </div>
</div>

asset/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asset</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

asset/app/views/logs/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

asset/app/views/logs/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

asset/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :タイトル %>
    <%= form.text_field :title, id: :user_title %>
  </div>

  <div class="field">
    <%= form.label :内容 %>
    <%= form.text_area :contents, id: :user_contents %>
  </div>

  <div class="field">
    <%= form.label :画像 %>
    <%= form.file_field :image %>
  </div>

   <div class="field">
    <%= form.label :住所 %>
    <%= form.text_field :address, id: :user_address %>
  </div>

  

  <div class="actions">
    <%= form.submit value: "投稿"%>
  </div>
<% end %>

asset/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to '詳細', @user %> |
<%= link_to '戻る', users_path %>

asset/app/views/users/home.html.erb
<%= button_to "ログイン", users_path, method: :get %>
<%= button_to "新規登録", new_log_registration_path, method: :get %>

asset/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>投稿一覧</h1>



<table>
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th>投稿日時</th>
      <th>住所</th>
      <th>画像</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.title %></td>
        <td><%= simple_format(user.contents) %></td>
        <td><%= user.created_at %></td>
        <td><%= user.address %></td>
        <td><%= image_tag user.image.to_s ,  :size =>'60x40' %></td>
        <td><%= link_to '詳細', user , class: 'btn'%></td>
        <td><%= link_to '編集', edit_user_path(user), class: 'btn' %></td>
        <td><%= link_to '削除', user, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn'%></td>
      </tr>
    <% end %>
  </tbody>

  


  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th>投稿日時</th>
      <th>住所</th>
      <th>画像</th>
      <th colspan="3"></th>
    </tr>
  </thead>
</table>
<br>





<div><%= link_to '新規投稿', new_user_path , class: 'btn'%></div>
<div> </div>
<div><%= link_to 'ログアウト', destroy_log_session_path, method: :delete, class: 'btn' %></div>

asset/app/views/users/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', users_path %>

asset/app/views/users/show.html.erb
<!-- 追加箇所開始 -->
<script type="text/javascript">
    function initMap() {

        var test = {lat: <%= 35.648428 %>, lng: <%= 139.702986 %>};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: test
        });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @address %>';
        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position:test,
            map: map,
            title: contentString
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCi_PcemdLaMhhvj1x6OuHg_Xhh1DCH1cc&callback=initMap">
</script>
<!-- 追加箇所終了 -->



<p id="notice"><%= notice %></p>



<p>
  <strong>タイトル:</strong>
  <%= @user.title %>
</p>

<p>
  <strong>内容:</strong>
  <%= @user.contents %>
</p>

<p>
  <strong>画像:</strong>
  
</p>
<p>
  <%= image_tag @user.image.to_s , :size =>'240x160' %>
</p>
<!-- 追加箇所開始 -->
<style type="text/css">
  #map { height: 400px;
    margin-left:auto;
    margin-right:auto;
    text-align:left;
    width: 80%;}
</style>
<div id="map"></div>
<!-- 追加箇所終了 -->

<%= link_to '編集', edit_user_path(@user) %> |
<%= link_to '戻る', users_path %>